project:
  type: website
  render: 
    - index.qmd
    - quant_talks.qmd
    - quant_talks
    - workshop.qmd
    - workshop
    - resources.qmd
    - others
    - flyers

website:
  title: "USC McArdle GC-3 Center"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: quant_talks.qmd
        text: "Quant Speaker Series"
      - href: workshop.qmd
        text: "Workshop"
      - href: resources.qmd
        text: "Resources"
  page-footer: 
    left: "© 2023 USC McArdle GC-3 Center"
    right: 
      - "Source code: "
      - icon: github
        href: https://github.com/usc-gc3/gc3site

format:
  html:
    theme: 
      - lumen
      - custom.scss
    css: styles.css
    toc: true

editor: visual

