---
title: "Quantitative Speaker Series"
---

## Spring 2025

| Date   | Topic                                                                                                                          | Speaker              |
|--------|--------------------------------------------------------------------------------------------------------------------------------|----------------------|
| Feb 13 | [A two-stage approach to account for measurement error when using random slopes as predictors](quant_talks/20250213_Mark_Lai.html)        | Mark Lai |
| Feb 20 | [Detecting Critical Change in Dynamics Through Outlier Detection with Time-Varying Parameters](quant_talks/20250220_Meng_Chen.html)        | Meng Chen |
| Feb 27 | [Patient-Centered Outcomes Research at Genentech](quant_talks/20250227_Coen_Bernaards.html)        | Coen Bernaards |
| Apr 10 | [AI and technology-based micro-experimental intervention for precision mental health](quant_talks/20250410_Addie_Timmons.html)        | Addie Timmons |
| Apr 18 | [A Few Things I’ve Learned About Multilevel Modeling (MLM) Over the Past 20 Years](quant_talks/20250418_Oi-man_Kwok.html)        | Oi-man Kwok |
| Apr 24 | [Exploring the potential of Large Language Models (LLMs) in early-stage test development](quant_talks/20250424_Meltem_Ozcan.html)        | Meltem Ozcan |
| May 1 | [From Data to Knowledge: AI/ML solutions to industry applications](quant_talks/20250501_Marianna_Graf.html)        | Marianna Graf |


## Fall 2024

| Date   | Topic                                                                                                                          | Speaker              |
|--------|--------------------------------------------------------------------------------------------------------------------------------|----------------------|
| Oct 31 | [Latent Factor Score Estimation With Missing Data](quant_talks/20241031_ehri_ryu.html)        | Ehri Ryu |
| Nov 14 | [Measuring the Unmeasurable? Psychometrics and Human Evaluation in Google Ads](quant_talks/20241114_jeremy_miles.html)        | Jeremy Miles |



## Spring 2024

| Date   | Topic                                                                                                                          | Speaker              |
|--------|--------------------------------------------------------------------------------------------------------------------------------|----------------------|
| Apr 26 | [Recent Advancements of Moderation and Mediation Analyses](quant_talks/20240426_kh_yuan.html)        | Ke-Hai Yuan |
| Apr 18 | [Elliptical Sampling as an Alternative to Extreme Group Designs](quant_talks/20240418_ryne_estabrook.html)        | Ryne Estabrook |
| Apr 4 | [Assessing the Validity of Behavioral Measures of Risk Taking](quant_talks/20240404_kevin_kapadia.html)        | Kevin Kapadia |
| Feb 15 | [Mapping Person-Item Interactions: A Latent Space Approach to Psychological Assessment Data with Interaction Maps](quant_talks/20240215_mj_jeon.html)        | Minjeong Jeon |



## Fall 2023

| Date   | Topic                                                                                                                          | Speaker              |
|--------|--------------------------------------------------------------------------------------------------------------------------------|----------------------|
| Dec 7 | [Disentangling multi-timescale latent processes in high-intensity repeated mobile cognitive assessments](quant_talks/20231207_zita_oravecz.html)        | Zita Oravecz |
| Nov 7 | [Latent Growth Factors as Predictors of Distal Outcomes: Completing the Triad](quant_talks/20231107_patrick_curran.html)        | Patrick J. Curran |
| Oct 19 | [Mom Genes: A new extended pedigree model for quantifying the contributions of mitochondrial DNA](quant_talks/20231019_mason_garrison.html)        | S. Mason Garrison |



## Spring 2023

| Date   | Topic                                                                                                                          | Speaker              |
|--------|--------------------------------------------------------------------------------------------------------------------------------|----------------------|
| Apr 20 | [Methodological considerations in data fusion using Bayesian synthesis](quant_talks/20230420_katerina_marcoulides.html)        | Katerina Marcoulides |
| Apr 6  | [Incorporating Meta-Science in the development of mediation and moderation analysis](quant_talks/20230406_amanda_montoya.html) | Amanda Montoya       |
| Mar 9  | [Estimating the standardized average treatment effect with missing outcome data](quant_talks/20230309_samantha_anderson.html)  | Samantha Anderson    |
| Feb 16 | [To what extent is there really a replication (and reproduction) crisis?](quant_talks/20230216_stephen_west.html)              | Stephen West         |

## Fall 2022

| Date   | Topic                                                                                                                                  | Speaker         |
|--------|----------------------------------------------------------------------------------------------------------------------------------------|-----------------|
| Dec 1  | [Measurement invariance testing in item factor analysis](quant_talks/20221201_kevin_grim.html)                                         | Kevin Grimm     |
| Nov 17 | [Some development and applications of longitudinal data analysis methods in psychology research](quant_talks/20221117_peggy_wang.html) | Peggy Wang      |
| Sep 22 | [Jack McArdle's influence on me and my work](quant_talks/20220922_sarfaraz_serang.html)                                                | Sarfaraz Serang |

## Spring 2022

| Date   | Topic                                                                                                                                 | Speaker       |
|--------|---------------------------------------------------------------------------------------------------------------------------------------|---------------|
| May 3  | [Prevalence, Influences, and Handling Methods of Non-normal Data](quant_talks/20220503_johnny_zhang.html)                             | Johnny Zhang  |
| Apr 19 | [Engineering an intervention to achieve *EASE*: The multiphase optimization strategy (MOST)](quant_talks/20220419_linda_collins.html) | Linda Collins |
| Mar 22 | [Measurement Practices, Metascience, and the Methodological Reform Movement](quant_talks/20220322_jessica_flake.html)                 | Jessica Flake |

## Fall 2021

+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Date   | Topic                                                                                                                                                                                                     | Speaker        |
+========+===========================================================================================================================================================================================================+================+
| Nov 16 | [A Discussion on The Uses of Power](quant_talks/20211116_jolynn_pek.html)                                                                                                                                 | Jolynn Pek     |
+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Oct 19 | [Applications of Data-Driven Methods for Studying Dynamic, Person-Specific processes](quant_talks/20211019_katie_gates.html)                                                                              | Kathleen Gates |
+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Oct 5  | [On networks and online Russian trolls:\                                                                                                                                                                  | Hudson Golino  |
|        | How can the total entropy ﬁt index be applied to optimize the number of embedded dimensions used in dynamic exploratory graph analysis, and why does it matter?](quant_talks/20211005_hudson_golino.html) |                |
+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+

## Spring 2021

| Date   | Topic                                                                                                                      | Speaker          |
|--------|----------------------------------------------------------------------------------------------------------------------------|------------------|
| Apr 27 | [Similar Predictions from Different Models: Exploring the Space of Model Similarity](quant_talks/20210427_chris_beam.html) | Christopher Beam |
| Mar 30 | [Cognition and Achievement: Isn't it about time we cancelled IQ?](quant_talks/20210330_nayena_blankson.html)               | Nayena Blankson  |
| Mar 2  | [Recent Progress on Bayesian Structural Equation Models](quant_talks/20210302_ed_merkle.html)                              | Ed Merkle        |
