---
title: "GC-3 Workshops"
---

## Fall 2025

+---------+------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------------------------------------+
| Date    | Topic                                                                                                                        | Speaker     | Download Materials                                     |
+=========+==============================================================================================================================+=============+========================================================+
| Sep 25  | First Rountable: Introducing GC3 rountable series and collecting ideas                                                       | Jimmy Zhang |                                                        |
+---------+------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------------------------------------+
| Oct 23  | [Second Rountable: Data visualization series (*Visualizing Group Comparisons*)](workshop/20251023_rt2_group_comparison.html) | Jimmy Zhang | [GC3_RT2](workshop/20251023_rt2_group_comparison.html) |
+---------+------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------------------------------------+
| Nov 6   | [Third Rountable: Data visualization series (*Layout and Composition of Multiple Plots*)](workshop/20251023_rt3_layout.html) | Jimmy Zhang | [GC3_RT3](workshop/20251023_rt3_layout.html)           |
+---------+------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------------------------------------+
| Nov 20  |                                                                                                                              |             |                                                        |
+---------+------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------------------------------------+

## Fall 2023

+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+--------------------+
| Date   | Topic                                                                                                                                                                                                         | Speaker  | Download Materials |
+========+===============================================================================================================================================================================================================+==========+====================+
| Oct 23 | [Robust Statistics: Why Your Statistical Analyses Might Be Completely Wrong. Chapter 1.1. Intro to Outliers](workshop/20231023_introOutliers.html) ([Recording](https://www.youtube.com/watch?v=D73AjnaQfEE)) | Sean Lee |                    |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+--------------------+
| Oct 22 | [Robust Statistics: Why Your Statistical Analyses Might Be Completely Wrong. Chapter 0. Robust?](workshop/20231022_introRobust.html) ([Recording](https://www.youtube.com/watch?v=_lApTobmNf4))               | Sean Lee |                    |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+--------------------+

## Spring 2023

+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+
| Date    | Topic                                                                                                                                                                                                                                                                            | Speaker             | Download Materials                                                                                      |
+=========+==================================================================================================================================================================================================================================================================================+=====================+=========================================================================================================+
| Mar 30  | [Dealing with Missing Data in R](workshop/20230330_missing_data.html)                                                                                                                                                                                                            | Yichi Zhang         | [github](https://github.com/YichiZhang2024/Missing_Data)\                                               |
|         |                                                                                                                                                                                                                                                                                  |                     | [google drive](https://drive.google.com/drive/folders/1KKRtMp3uvO16ESl1lt391xSspqGCu8st?usp=share_link) |
+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+
| Mar 2   | [From Scratch to Deployment: Making Your Personal Website With R](workshop/20230302_website_creation.html) ([Recording](https://usc.zoom.us/rec/play/xVcr_eCyhoIu0ccTGqz98GcLA9ZxDNRiSAtGzSeyvb1q8x_cEGjOUNlmOykrwyZFgc9Y8cEdVTCuTRQ7.Go4aknp4--yqNVJD?startTime=1677787309000)) | Winnie Wing-Yee Tse | [google drive](https://drive.google.com/drive/folders/1b477f2L9nLzG5p-PamEgnde__Ks1bV_l?usp=share_link) |
+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+

## Fall 2022

+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+
| Date    | Topic                                                                                                                                                                                                                 | Speaker             | Download Materials                                                                                      |
+=========+=======================================================================================================================================================================================================================+=====================+=========================================================================================================+
| Nov 3   | [Measurement Invariance Testing](workshop/20221103_measurement_invariance.html)                                                                                                                                       | Yichi Zhang         | [github](https://github.com/YichiZhang2024/GC-3-workshop-Measurement-Invariance)\                       |
|         |                                                                                                                                                                                                                       |                     | [google drive](https://drive.google.com/drive/folders/1iyddBrb_GjVl2roJ2XCsbK2PGbyVmWg3?usp=share_link) |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+
| Oct 20  | [Data Wrangling and Visualization in R](workshop/20221020_data_wrangling.html)                                                                                                                                        | Winnie Wing-Yee Tse | [github](https://github.com/winniewytse/gc3-tidyverse-workshop)\                                        |
|         |                                                                                                                                                                                                                       |                     | [google drive](https://drive.google.com/drive/folders/1H11lYdka0uNMulTloxrS2fz6yS-DQp2Y?usp=share_link) |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+
| Oct 6   | [Structural Equation Modeling](workshop/20221006_SEM.html)                                                                                                                                                            | Jimmy Zhang         |                                                                                                         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+
| Sep 8   | [Making Poster with R](workshop/20220908_poster.html) ([Recording](https://usc.zoom.us/rec/play/nfaj5Md_Xi2VCR0lFsgR5jD1QS-Dg12D2emOtKjCkH38esWMP-qLCh0MGL-nG7ASKhLZPpA2CVbQ6hs2.I4XgJ31BanW-MthN?continueMode=true)) | Jimmy Zhang         |                                                                                                         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------------------+

<!-- SEM -->

<!-- [github](https://github.com/Gengrui-Zhang/GC3_IntroSEM)\ -->

<!-- [google drive](https://drive.google.com/drive/folders/1_C8g9k0gEYpD_Q7n711u0_aElB4J4dKv?usp=share_link) -->

<!-- Poster -->

<!-- [github](https://github.com/Gengrui-Zhang/PosterExample) -->
