---
title: "Cognition and Achievement: Isn't it about time we cancelled IQ?"
subtitle: "USC Quantitative Speaker Series (Spring 2021)"
---

**Date: March 30, 2021**

**Speaker: A. Nayena Blankson, Ph.D.**

Professor of Psychology\
Spelman College

[**Video Recording**](https://drive.google.com/file/d/1iGVYBRLDzfOBxrUavZdY5ZVcaBWPw6xm/view?usp=share_link) (requires sign in using your USC NetID)

### Abstract

In this presentation, Dr. Blankson will discuss research on achievement in children. She will present background on what we know in the field, present reasons why we should "cancel" IQ, and suggest directions for future research.

### Bio

Dr. A. Nayena Blankson is a Full Professor at Spelman College. She received her Ph.D. in quantitative psychology from the University of Southern California. Her research interests straddle both quantitative and developmental psychology. Her developmental research interests include the organization and development of cognitive abilities as it relates to personality, parenting, schooling, and early academic achievement. Her quantitative interests include psychometrics, multivariate methods, moderated mediation, the design of psychological research, and structural equation modeling. Dr. Blankson is the director of the Cognition and Temperament (CAT) Lab at Spelman (Research funded by NIH R15HD077511 and NSF Award #1832090); She is the Director of the INSPIRE U2 summer REU site (NSF Award #1852056); and she is Program Director of the Spelman RISE Program (NIH R25GM060566).
